# Generated by Django 2.0.3 on 2018-03-19 17:18

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imagehashes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_hash', models.CharField(max_length=16)),
                ('image_words', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
